# Generated by bin/sync-shared.sh - do not edit.
# Source of truth: backend/_shared/database.py
"""
PostgreSQL access plumbing shared by every service (model layer).

Holds one connection per Lambda container and reuses it across invocations.
Models build their SQL on top of the helpers here; they never open connections
themselves.
"""

import logging
import os
from contextlib import contextmanager

from psycopg import connect
from psycopg.rows import dict_row

logger = logging.getLogger()

IS_LOCAL = os.getenv("IS_LOCAL", "false") == "true"

# Aurora requires TLS; the local PostgreSQL install does not offer it.
PG_CONFIG = (
    f"host={os.getenv('POSTGRES_HOST', 'localhost')} "
    f"port={os.getenv('POSTGRES_PORT', '5432')} "
    f"user={os.getenv('POSTGRES_USER', 'postgres')} "
    f"password={os.getenv('POSTGRES_PASS', 'postgres123')} "
    f"dbname={os.getenv('POSTGRES_NAME', 'postgres')} "
    f"sslmode={'disable' if IS_LOCAL else 'require'} "
    f"connect_timeout=15"
)

# Reused between invocations within the same Lambda container.
_CONN = None

def get_connection():
    """Return the pooled connection, opening one if needed."""
    global _CONN
    if _CONN is None or _CONN.closed:
        _CONN = connect(PG_CONFIG, row_factory=dict_row)
    return _CONN

def reset_connection():
    """Drop the pooled connection so the next call reconnects."""
    global _CONN
    if _CONN is not None and not _CONN.closed:
        try:
            _CONN.close()
        except Exception:  # pragma: no cover - closing a broken socket
            pass
    _CONN = None

@contextmanager
def cursor(commit=False):
    """
    Yield a cursor and close out its transaction.

    psycopg does not autocommit, and the connection outlives the invocation, so
    every block must end in a commit or a rollback. Leaving one open would hold
    a transaction (and its locks) until the container is recycled.

    Args:
        commit (bool): commit on success; otherwise roll back
    """
    conn = get_connection()
    try:
        with conn.cursor() as cur:
            yield cur
        if commit:
            conn.commit()
        else:
            # Read-only work still opened a transaction; end it so the next
            # invocation does not reuse a stale snapshot.
            conn.rollback()
    except Exception:
        try:
            conn.rollback()
        except Exception:
            # The connection itself is broken - force a reconnect next time.
            reset_connection()
        raise

def fetch_all(sql, params=None):
    """Run a query and return every row as a dict."""
    with cursor() as cur:
        cur.execute(sql, params or ())
        return cur.fetchall()

def fetch_one(sql, params=None):
    """Run a query and return the first row as a dict, or None."""
    with cursor() as cur:
        cur.execute(sql, params or ())
        return cur.fetchone()

def execute(sql, params=None, returning=False):
    """
    Run a write and commit it.

    Args:
        sql (str): statement to run, with %s placeholders
        params (tuple, optional): values for the placeholders
        returning (bool): True when the statement has a RETURNING clause

    Returns:
        dict | int: the returned row, or the number of rows affected
    """
    with cursor(commit=True) as cur:
        cur.execute(sql, params or ())
        return cur.fetchone() if returning else cur.rowcount

@contextmanager
def transaction():
    """
    Yield a cursor whose statements commit together.

    Use it when two writes must both land or neither, such as a status change
    and the system message that records it.
    """
    with cursor(commit=True) as cur:
        yield cur
